### ISSUE TITLE
add bower to release process

### ISSUE THREAD

**Issue by peter-mouland** [ft-interactive/o-charts#54]
include `o-charts` and `o-charts.min.js` in a `dist` folder and ensure bower has this folder
 * do not include `dist` in the `master` branch in git
 * update readme to tell people how to install locally
 * ensure this works with d3
 * ensure people do not have to use a build tool

**Comment by kavanagh** [comment]
today we decided we don't need a dist folder.

**Comment by radiodario** [comment]
sounds fair enough

**Comment by alexgraul** [comment]
Would you guys be open to a PR to do bower or npm package support?

**Comment by kavanagh** [comment]
@alexgraul Yes we fully intend to do that soon. There are a couple of improvements needed in the release process, this includes publishing to npm.  If you fancy making a PR then please go ahead, alternatively you can just point you package.json to the repo until we do it.

* **Npm**: yes definitely, it's fairly easy.
* **Bower**: ok, but we assume you'll use Browserify or Webpack. We are not going to have built code in this repo.

It would be interesting to know what attracts you to this library, how you'd use it and any thoughts you have. If you do actually find yourself making use of it do tell us how you get on.

Also, as a warning, I'd say that we have notional plans to change the interface a little for V1. At the moment the API is experimental and a little messy. I'd like to make the individual parts more modular, allow for extension, mixing with other libraries and theming with non-FT styled charts. We are also pondering the use of ES6 modules, inline with other FT code and D3 v4. Thoughts on this are welcome too.

**Comment by alexgraul** [comment]
Would prefer NPM to bower so that's all good. In terms of appeal - it's works more in concert with the d3 ecosystem that a lot of d3 based charting libs, which attempt to wrap d3 instead. We'd be looking to develop our own theme and then essentially wrap charts up as ember components - whether we'd be better off simply forking is an open question but I think it would be possible for us to use the library and then contribute back.

**Comment by peter-mouland** [comment]
Hope all is well your end!I assume this issue can be closed? It's not solved yet which suggest it's not a big deal?

**Comment by kavanagh** [comment]
👋  Hey! o-charts is parked. Probably some action in the coming months. My view is follow D3 v4 lead and decompose this library, also allow rollup compatibility. Close for now is a good idea. Thanks
