### ISSUE TITLE
Key on grouped columns should be horizontally aligned.

### ISSUE THREAD

**Issue by kavanagh** [ft-interactive/o-charts#86]
The idea is that the order the colours and labels appear in a key should mirror how they are in the plot. Otherwise reading the chart requires the user to do a mental remap.

![image](https://cloud.githubusercontent.com/assets/684559/8675254/b92a24e8-2a3a-11e5-8f70-91044dd80497.png)

Note that you cannot do this for scatter plots so best to give user option of vertical or horizontal depending on what makes most sense with the data.

**Comment by radiodario** [comment]
Yep we have this coming up next on the backlog!

**Comment by peter-mouland** [comment]
now in o-charts' soon to be in nightingale
