### ISSUE TITLE
integrate s3 into the release process

### ISSUE THREAD

**Issue by peter-mouland** [ft-interactive/o-charts#89]
this would give a place for the compiled code somewhere to live

**Comment by kavanagh** [comment]
Prefer either:

1. Do just enough work to get o-charts via the Origami build service (Most ideal) 
2. Use Github to host code via the releases API.

Otherwise the original request, to easily get a built JS file, seems to subvert Origami and bower.

**Comment by peter-mouland** [comment]
makes sense, will close this in favor of origami
